//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public Conductor()
        {
            this.Conductor_Vehiculo = new HashSet<Conductor_Vehiculo>();
        }
    
        public int IdConductor { get; set; }
        public string Nombre { get; set; }
        public string TipoDocumento { get; set; }
        public string Documento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<Conductor_Vehiculo> Conductor_Vehiculo { get; set; }
    }
}
