//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPM.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor_Vehiculo
    {
        public int Id { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
